-- Migration: initial_schema
-- Project: Scent Stories
-- Generated by: Database Engineer Agent

BEGIN;

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Ensure the leads table exists with the specified schema
-- Note: If table already existed with different column names (e.g. email_address), 
-- it was corrected during application to align with the Feature Technical Document.

CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── INDEXES ─────────────────────────────────────────────────────────────────

-- Index for email lookups and unique constraint efficiency
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Insert: Allowed for anon role (public submissions)
IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'leads' AND policyname = 'Allow public lead submissions'
) THEN
    CREATE POLICY "Allow public lead submissions" ON leads
      FOR INSERT 
      WITH CHECK (true);
END IF;

COMMIT;