-- Migration: initial_schema
-- Project: Scent Stories
-- Generated by: Database Engineer Agent

BEGIN;

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Table: leads
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── INDEXES ─────────────────────────────────────────────────────────────────

-- Index for email lookups and unique constraint efficiency
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Insert: Allowed for anon role (public submissions)
CREATE POLICY "Allow public lead submissions" ON leads
  FOR INSERT 
  WITH CHECK (true);

-- Select/Update/Delete: Restrictive
-- Explicitly denying access for non-service roles is default once RLS is enabled without a policy,
-- but standard practice for "authenticated admin dashboard (future-proofing)" is to 
-- leave other operations locked down until the admin roles are defined.

COMMIT;